### ISSUE TITLE
Pysam version

### ISSUE THREAD

**Issue by johnstonmj** [hoffmangroup/polyidus#10]
Hi Mehran,

I am encountering the following error in each run:
```
Traceback (most recent call last):
  File "/home/michael.johnston1/software/polyidus/src/polyidus.py", line 139, in <module>
    args.outdir, args.aligner, args.virname, args.skip_alignment)
  File "/home/michael.johnston1/software/polyidus/src/polyidus.py", line 84, in main
    polyidusObj.find_exact_integrations()
  File "/home/michael.johnston1/software/polyidus/src/utils.py", line 1005, in find_exact_integrations
    start_host, readnames)
  File "/home/michael.johnston1/software/polyidus/src/utils.py", line 90, in get_host_pos
    chromsize = bam.header.get_reference_length(chromhost)
AttributeError: 'dict' object has no attribute 'get_reference_length'
```

The error appears to be coming from utils.py line 90 where:
```
    chromsize = bam.header.get_reference_length(chromhost)
    lower_bound = max([0, start_host - 2000])
    upper_bound = min([start_host + 2000, chromsize])
```

Your Quick Start instructions specify pysam (v0.8.4).
In my testing with this pysam version, 'bam.header' is just a dictionary with key 'SQ' containing reference sequence lengths. Neither object 'bam' nor 'bam.header' appear to have the method 'get_reference_length'.

Upgrading to pysam=0.16 fixed this error for me.

Perhaps the get_reference_length method was added after pysam 0.8.4?

Hope this helps,

- Michael

**Comment by mehrankr** [comment]
Hi Michael,

Thanks for pointing this out. I will release an update soon and will clarify the pysam version requirement.

Mehran

**Comment by johnstonmj** [comment]
Hi Mehran,

In case it helps, here is the conda environment I am using now.
Polyidus runs error-free:

```
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bowtie2 = 2.2.6
  - samtools = 1.9
  - pysam = 0.15
  - bedtools = 2.26
  - python = 3.5
  - psutil = 5.4
  - numpy = 1.15
  - pandas = 0.23
```

Cheers
Michael

**Comment by mehrankr** [comment]
Thank you Michael. Polyidus now requires pysam >= 0.15 and this is added to the documentation on today's push.
