### ISSUE TITLE
Software Dependency Conflicts

### ISSUE THREAD

**Issue by DAWNkKim** [hoffmangroup/polyidus#13]
Hello, I am a user living in South Korea.

I tried to install the required programs as mentioned in the README.rst like below.
conda install -c bioconda bowtie2=2.2.6
conda install -c bioconda samtools=1.9
conda install -c bioconda pysam=0.15.0
conda install -c bioconda bedtools=2.26.0
conda install -c anaconda pandas=0.22.0
conda install -c anaconda numpy=1.18.1
conda install -c conda-forge psutil=5.4.3

However, I got an error saying that numpy requires python=3.6 or higher (to use which). 

So I installed samtools, pysam, bedtools, pandas, numpy, and psutil all with py=3.6 in the new environment, and bowtie2 says it needs python 3.4 or 3.5 or 2.7. 

Which python version should I use?

+ I can't proceed with bowtie2, so I tried to proceed with bwa, but bwa doesn't run properly and seems to terminate. can anyone tell me if polyidus uses mem or aln for mapping using bwa?

The reason I thought BWA didn't run properly is because it didn't generate any output files in viral/, results/, host/, etc., including /viral/virusAligned-temp.bam.

**Comment by mehrankr** [comment]
Hello,

I apologize for not getting back to you earlier.

It's best if you start from a completely new conda environment to setup the requirements.
Numpy and pandas version are generally quite flexible, and pysam is the least flexible of all.
I would make sure your pysam and samtools version are similar, and most other things should work fine.

The tool is not compatible with bwa; please use bowtie2.

**Comment by DAWNkKim** [comment]
Thank you for your response. Based on the information provided, I created a new environment with a fresh perspective and followed the steps below for installation. Everything installed without any issues:

conda install -c bioconda pysam=0.15.0
conda install -c bioconda samtools=1.9
conda install -c bioconda bedtools=2.26.0
conda install -c conda-forge psutil=5.4.3
conda install -c anaconda numpy
conda install -c anaconda pandas
conda install -c bioconda bowtie2

Thank you! :)
