### ISSUE TITLE
Python module dependencies

### ISSUE THREAD

**Issue by johnstonmj** [hoffmangroup/polyidus#2]
Hi,

I was trying to test out Polyidus and encountered errors with missing python modules.

The dependencies list:
bowtie2 (v2.2.6), samtools (v1.9), pysam (v0.8.4), and bedtools (v2.26.0)

However, I needed to include the following python modules as well:
psutil, numpy, and pandas

**Comment by mehrankr** [comment]
Thanks for raising this. It's fixed as of the latest commit on May 16th
