### ISSUE TITLE
Late Stage Out of Memory

### ISSUE THREAD

**Issue by johnstonmj** [hoffmangroup/polyidus#5]
While running Polyidus with 20 GB memory, it failed with:
`slurmstepd: error: Detected 1 oom-kill event(s) in step 5569557.batch cgroup.`

The failure occurred after running for 28 hrs, when files `hostAligned_sorted.bam` and `hostAligned_sorted.bam.bai` already exist.

As such, I have three questions:
**1 - Does using >20 GB memory make sense?**
The README specifies 4 GB memory usage.
Is there possibly some other error leading to this?

**2 - Could Polyidus be split into two modules?**
The "early" progress with bowtie2 and samtools to generate bams and fastqs does not require much memory, but could potentially be multi-threaded with bowtie2 + samtools.
The "late" progress seems to operate on a single CPU but with significant memory usage.
Running on a cluster, my server admins don't like it when I've got long-duration jobs that don't efficiently use all resources requested. Splitting into two modules would allow me to specify different job resource requirements for early (low memory, multi-CPU) and late (single CPU, high memory).

**3 - Alternatively, can Polyidus be checkpointed to allow restart from intermediate progress?**
I would like to use the existing `hostAligned_sorted.bam`, `ViralAligned_1.fastq`, and `ViralAligned_2.fastq` without needing to wait another 24 hrs for them to be recreated.

Please let me know what you think.
Any help would be appreciated!

**Comment by mehrankr** [comment]
I added a new parameter --skip-alignment that will skip alignment if the expected files exist. Could you please try and let me know if it works? I will keep the issue open in the meanwhile.

**Comment by mehrankr** [comment]
Passes the tests now. Please open a new issue if you encounter an error.
