### ISSUE TITLE
ValueError: start out of range

### ISSUE THREAD

**Issue by johnstonmj** [hoffmangroup/polyidus#6]
Hi,

I believe I am encountering errors with alignments near to the ends of chromosomes.

Error message:
```
Traceback (most recent call last):
  File "/home/michael.johnston1/software/polyidus/src/polyidus.py", line 118, in <module>
    args.outdir, args.aligner)
  File "/home/michael.johnston1/software/polyidus/src/polyidus.py", line 73, in main
    polyidusObj.find_exact_integrations()
  File "/home/michael.johnston1/software/polyidus/src/utils.py", line 1024, in find_exact_integrations
    start_host, readnames)
  File "/home/michael.johnston1/software/polyidus/src/utils.py", line 89, in get_host_pos
    for read in bam.fetch(chromhost, start_host - 2000, start_host + 2000):
  File "pysam/calignmentfile.pyx", line 860, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10789)
  File "pysam/calignmentfile.pyx", line 788, in pysam.calignmentfile.AlignmentFile.parse_region (pysam/calignmentfile.c:10349)
ValueError: start out of range (-940)
```

My prediction is that a `start_host` value less than 2000 bp from a chromosome end causes `bam.fetch` to go beyond the ends of the chromosome.

Perhaps having bam.fetch use something like:
`max(0, start_host - 2000)` 
(possibly `max(1, start_host - 2000)` depending on the coordinates used at this point)
and
`min(chr_length, start_host + 2000)`
would fix this?

Thanks as always!

**Comment by mehrankr** [comment]
Thanks for reporting this. I will fix this and the previous issue over this weekend and will get back to you.

**Comment by mehrankr** [comment]
Could you please try again with the most recent commit on May 23rd?

**Comment by johnstonmj** [comment]
Hi Mehran,
Thank you so much for helping to address this.
I apologize for my delayed response.

I have just tested and I now encounter a new error that occurs very quickly.

> Traceback (most recent call last):
>   File "/home/michael.johnston1/software/polyidus/src/polyidus.py", line 140, in <module>
>     args.outdir, args.aligner, args.virname, args.skip_alignment)
>   File "/home/michael.johnston1/software/polyidus/src/polyidus.py", line 69, in main
>     fastq, outdir, aligner, virname)
>   File "/home/michael.johnston1/software/polyidus/src/utils.py", line 715, in __init__
>     self.outdir_viral, "virusAligned-temp.bam")
> AttributeError: 'polyidusEngine' object has no attribute 'outdir_viral'

Perhaps something got broken in the input argument parsing?

**Comment by mehrankr** [comment]
Thanks for taking a look. I think I know what caused the problem. It now passes the test on my end so it should be fine. I'll close the issues for now. Please open a new one if there are more issues.
